### ISSUE TITLE
superclass mismatch for SpatialPostgreSQLColumn

### ISSUE THREAD

**Issue by djberg96** [pdeffendol/spatial_adapter#17]
Hi,

Rails 2.3.4, Ruby 1.8.7, spatial_adapter 1.1.2

I added spatial_adapter to environment.rb file, fired up script/console and got this:

/usr/local/lib/ruby/gems/1.8/gems/spatial_adapter-1.1.2/lib/spatial_adapter/postgresql.rb:328:TypeError: superclass mismatch for class SpatialPostgreSQLColumn

Any ideas?

Regards,

Dan

**Comment by pdeffendol** [comment]
I haven't seen that one before.  I'll run the specs for Rails 2.3.4 and see what I can find.

**Comment by pdeffendol** [comment]
This isn't happening for me with a new Rails 2.3.4 app that loads spatial_adapter in the environment.rb file.  Typically that Ruby error happens when you try to open up a class and specify the wrong parent class (superclass).

Do you have an older version of spatial_adapter loaded somewhere else at the same time?  Perhaps in vendor/plugins?

**Comment by pdeffendol** [comment]
No response, closing.
