### ISSUE TITLE
Why test RAILS_ENV in init.rb

### ISSUE THREAD

**Issue by pdeffendol** [pdeffendol/spatial_adapter#2]
I'm not really sure why we're looking at RAILS_ENV and the current ActiveRecord connection in init.rb.  Why not just patch both PostgreSQL and MySQL all the time?  This would give the ability to use ActiveRecord and the spatial_adapter outside of Rails.

**Comment by JohnSmall** [comment]
Quite right. I found it a nuisance to have to have a different block of code to initialize the plugin when testing just the plugin outside the full Rails environment. The only reason I left the version using RAILS_ENV in there is because I though you'd put it there for a reason. It wasn't in the code I was using from my original download from SourceForge.

If this is to be used outside of Rails then it should be turned into a gem. I'll do that over the weekend if you want.

**Comment by pdeffendol** [comment]
Part of the trouble is that both the MySQL and the PostGIS adapters are monkey-patching ActiveRecord::Base.  I haven't looked at it in much detail yet, but that approach makes it hard to implement the plugin so that both the MySQL and PostGIS functionality is enabled at the same time.

**Comment by JohnSmall** [comment]
OK, I didn't think of that. I wouldn't use MySQL for GIS if PostGIS is available, but I guess there could be circumstances where people want to be able to use both at the same time to transfer geo-date between them. I'd ignore that use case unless someone wants it.

**Comment by pdeffendol** [comment]
I've started refactoring the code - it's on the "next" branch right now until the previous feature are re-implemented.  Currently only the PostGIS side of things is implemented, except for the enhanced find_by methods.  (That's the part that prevents both adapters from being loaded at once.)

**Comment by pdeffendol** [comment]
0.2.0 removes the Rails dependency
