### ISSUE TITLE
to_fixture_format not supported?

### ISSUE THREAD

**Issue by cwise** [pdeffendol/spatial_adapter#23]
The docs imply that to_fixture_format is a supported method, but it doesn't seem to be available. A look through the README indicates support might've been dropped for that at one point. What are the issues in restoring that?

**Comment by pdeffendol** [comment]
Yeah, that method was removed over a year ago because it was implemented differently for each database type, and was one of many things preventing one from using more than one database in a single application.  (https://github.com/fragility/spatial_adapter/commit/37f115493bfb6b4c86c68e02f4aa1b7552a41622)

Have you tried a fixture without the call to #to_fixture_format?  (I'm not sure if that works - let me know.)

```
fixture:
  id: 1
  data: HELLO
  geom: <%= Point.from_x_y(123.5,321.9) %>
```

**Comment by cwise** [comment]
Unfortunately that blows up. But... I did copy the old code and found that was a reasonable workaround for now.

**Comment by pdeffendol** [comment]
Thanks for the info.  Basically to make it work again, there needs to be a common fixture format that would be understandable by all databases involved.  

If you're using PostgreSQL, you can use <%= Point.from_x_y(123.5,321.9).as_hex_ewkb %> in the fixture.
